extends SceneTree

const T := preload("res://tests/_test_util.gd")

const BALLISTICS_SCRIPT_PATH := "res://city_game/combat/artillery/CityArtilleryBallistics.gd"

func _init() -> void:
	call_deferred("_run")

func _run() -> void:
	var ballistics_script = load(BALLISTICS_SCRIPT_PATH)
	if not T.require_true(self, ballistics_script != null, "Artillery ballistic round-trip contract requires CityArtilleryBallistics.gd"):
		return

	var ballistics = ballistics_script.new()
	if not T.require_true(self, ballistics != null, "Artillery ballistic round-trip contract requires CityArtilleryBallistics.gd to instantiate"):
		return

	if not T.require_true(self, ballistics.has_method("build_firing_solution_from_angles"), "Round-trip contract requires build_firing_solution_from_angles()"):
		return
	if not T.require_true(self, ballistics.has_method("predict_impact_from_firing_solution"), "Round-trip contract requires predict_impact_from_firing_solution()"):
		return
	if not T.require_true(self, ballistics.has_method("solve_firing_solution_to_target"), "Round-trip contract requires solve_firing_solution_to_target()"):
		return

	var source_solution := ballistics.build_firing_solution_from_angles(
		Vector3(140.0, 58.0, -220.0),
		123.5,
		24.5,
		"m795_he"
	) as Dictionary
	var predicted := ballistics.predict_impact_from_firing_solution(source_solution) as Dictionary
	if not T.require_true(self, bool(predicted.get("valid", false)), "Round-trip contract requires a valid source prediction before the inverse solve can be checked"):
		return

	var solved := ballistics.solve_firing_solution_to_target(
		source_solution.get("origin_world_position", Vector3.ZERO) as Vector3,
		predicted.get("impact_world_position", Vector3.ZERO) as Vector3,
		{
			"shell_type_id": "m795_he",
			"prefer_high_arc": false,
		}
	) as Dictionary
	if not T.require_true(self, bool(solved.get("solved", false)), "Round-trip contract requires inverse solve to recover an in-range target generated by the same gameplay model"):
		return
	if not T.require_true(self, absf(float(solved.get("world_bearing_deg", -999.0)) - 123.5) <= 0.05, "Round-trip solve must recover the source world bearing so future target-designation flows are not forced to drift bearing over time"):
		return
	if not T.require_true(self, absf(float(solved.get("pitch_deg", -999.0)) - 24.5) <= 0.05, "Round-trip solve must recover the source low-arc pitch when prefer_high_arc is false"):
		return

	var solved_prediction := ballistics.predict_impact_from_firing_solution(solved.get("firing_solution", {}) as Dictionary) as Dictionary
	if not T.require_true(self, bool(solved_prediction.get("valid", false)), "Round-trip contract requires the solved firing_solution to be immediately reusable by the forward solver"):
		return
	if not T.require_true(self, (solved_prediction.get("impact_world_position", Vector3.INF) as Vector3).distance_to(predicted.get("impact_world_position", Vector3.ZERO) as Vector3) <= 0.5, "Round-trip contract requires target -> solve -> predict to land back on the original predicted impact instead of diverging into a second ballistic branch"):
		return

	T.pass_and_quit(self)
